# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.

version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/squegg-api

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:

  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 600
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 600
      runas: root      
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 600
      runas: root
